In [8]:
import numpy as np
arr=np.arange(12).reshape(3,4)
mask=np.array([1,0,1],dtype=np.bool)
print(arr[mask,1])
print(mask)

[1 9]
[ True False  True]


C:\Users\admin\AppData\Local\Temp/ipykernel_39280/1614584736.py:3: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  mask=np.array([1,0,1],dtype=np.bool)


In [9]:
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [10]:
print(np.where([[True,False],[True,True]],[[1,2],[3,4]],[[9,8],[7,6]]))

[[1 8]
 [3 4]]


In [14]:
w=np.array([2,5,6,3,10])
print(w)
print(np.where(w>4))

[ 2  5  6  3 10]
(array([1, 2, 4], dtype=int64),)


In [ ]:
import numpy as np
 
a = np.arange(12).reshape(3,4)
print(a)
print(np.where(a > 5))
# print('a[np.where(a > 5)]:', a[np.where(a > 5)])
# print('np.where(a > 5)[0]:', np.where(a > 5)[0])
# print('np.where(a > 5)[1]:', np.where(a > 5)[1])
# print(a[np.where(a > 5)[0], np.where(a > 5)[1]])

### 3.1.1 NumPy数据类型

- array对象（数组）

In [1]:
import numpy as np
data=[3,-4,7,12] 
x = np.array(data) #使用列表生成一维数组
print(x)

[ 3 -4  7 12]


In [2]:
data = [[1,2], [3,4], [5,6]]
y = np.array(data) #使用列表生成二维数组
print(y)

[[1 2]
 [3 4]
 [5 6]]


In [1]:
import numpy as np
a=np.arange(0,1,0.1) #0到1（不包括1），步长取0.1
print(a)
b = np.arange(10).reshape(2,5) #0到10（不包含10），化为2行5列的数组
print(b)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


- matrix对象（矩阵）

In [11]:
data1=np.mat(np.zeros((3,3)))
print(data1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
data2= np.mat(np.ones((2,4))) #默认是浮点型的数据，如果需要时int类型，可以使用dtype=int。
print(data2)
print(type(data2))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<class 'numpy.matrix'>


In [13]:
data3=np.mat(np.random.rand(2,2)) #随机生成数据形成一个二维数组，转化为matrix
print(data3)

[[0.12144562 0.40117539]
 [0.67892958 0.73631232]]


In [15]:
data4=np.mat(np.random.randint(10,size=(3,3))) #随机整数
print(data4)

[[1 1 4]
 [7 3 9]
 [4 7 9]]


In [16]:
data5=np.mat(np.random.randint(2,8,size=(2,5))) #产生一个2-8之间的随机整数矩阵
print(data5)

[[2 3 6 4 6]
 [4 2 4 5 3]]


In [17]:
data6=np.mat(np.diag([1,2,3])) #生成一个对角线为1、2、3的对角矩阵。
print(data6)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


### 3.1.2  NumPy基本运算

- array基本运算

In [21]:
a= np.arange(3,11,2)#3到11（不含11），步长为2
b= np.array([1,4,3,2])
print(a)
print(a+b)
print(a*b)

[3 5 7 9]
[ 4  9 10 11]
[ 3 20 21 18]


In [1]:
import numpy as np
a = np.array([[1,2,3],[3,4,1]])
b = np.arange(6).reshape(2,3)
print(a,'\n',b)

[[1 2 3]
 [3 4 1]] 
 [[0 1 2]
 [3 4 5]]


In [2]:
print(a+b)
print(a-b)

[[1 3 5]
 [6 8 6]]
[[ 1  1  1]
 [ 0  0 -4]]


In [3]:
print(a*b)
print(a**3)
print(2*a)

[[ 0  2  6]
 [ 9 16  5]]
[[ 1  8 27]
 [27 64  1]]
[[2 4 6]
 [6 8 2]]


In [5]:
import numpy as np
a=np.array([0,1,2,3])
b=np.array([2,1,3,-2])
c=np.array([[4, 3], [2, 1]])
d=np.array([[1, 2], [3, 4]])
print('一维数组乘法：',a*b)
print('一维数组点积：',np.dot(a,b))

一维数组乘法： [ 0  1  6 -6]
一维数组点积： 1


In [6]:
print('二维数组乘法：\n',c*d)
print('二维数组点积：\n',np.dot(c,d))

二维数组乘法：
 [[4 6]
 [6 4]]
二维数组点积：
 [[13 20]
 [ 5  8]]


- matirx基本运算

In [7]:
import numpy as np
a=np.mat([[4,3,5,-4],[2,1,4,0]])
print(a.transpose())#两种都是转置
print(a.T)

[[ 4  2]
 [ 3  1]
 [ 5  4]
 [-4  0]]
[[ 4  2]
 [ 3  1]
 [ 5  4]
 [-4  0]]


In [8]:
import numpy as np
a = np.mat([[1,0,0],[3,4,0],[1,2,3]])
print(np.linalg.inv(a)) #两种都是矩阵求逆
print(a.I)

[[ 1.          0.          0.        ]
 [-0.75        0.25       -0.        ]
 [ 0.16666667 -0.16666667  0.33333333]]
[[ 1.          0.          0.        ]
 [-0.75        0.25       -0.        ]
 [ 0.16666667 -0.16666667  0.33333333]]


### 3.1.3 生成随机数常用函数

- Uniform()函数

In [10]:
import numpy as np
print(np.random.uniform())  #默认为0到1
print(np.random.uniform(1,5)) #生成1到5之间的float数
print(np.random.uniform(1,5,4)) # 生成一维数组

0.316558072015939
2.9592362528890477
[3.36508466 4.41936459 2.23860473 3.65809238]


In [12]:
print(np.random.uniform(1,5,(4,3))) # 生成4×3的数组

[[3.68912761 2.13402697 3.14837859]
 [1.76270574 3.21754111 2.09700625]
 [4.59067037 3.58691729 1.93655025]
 [4.29027732 2.82582793 3.50453854]]


In [13]:
print(np.random.uniform([1,5],[5,10])) #生成2个元素的一维数组

[1.03702846 9.71468384]


- randint()函数

In [15]:
 import numpy as np
print(np.random.randint(5)) #生成0~5之间的整数
print(np.random.randint(5,size=4)) #生成0~5之间的4个元素数组
print(np.random.randint(5,10,size=6)) #生成5~10之间的6个元素数组

1
[3 1 1 4]
[5 8 7 6 7 8]


In [16]:
print(np.random.randint(5,10,size=(2,3),dtype='int')) #生成5~10之间的2×3数组

[[8 8 6]
 [9 7 7]]


In [17]:
#随机函数生成验证码
import random
#从一个字符串中随机生成若干个字符
def gen_code(n):
    s='er0dfsdfxcvbn7f989fd'
    code=''
    for i in range(n):
        r = random.randint(0,len(s)-1)
        code+=s[r]
    return code
username=input("输入用户名：")
passwd=input("输入密码:")
code=gen_code(5)
print("验证码是：",code)
code1=input("输入验证码：")
if code.lower() == code1.lower():
    if username=='knn' and passwd=='abc':
        print("Login success!")
    else:
        print("username or password error！")
else:
    print("check code error!")

输入用户名：user
输入密码:1234
验证码是： bdr0d
输入验证码：bdr0d
username or password error！


### 3.1.4 对象转换

- 列表与字符串相互转换

In [18]:
#列表转换为字符串示例。
lst1=['This','is','a','apple']
print(' '.join(lst1))
#如果列表包含数字类型元素时，需要先转换为字符串
lst2=['S6','许文秀','女',21,'计算机系']
print(' '.join([str(x) for x in lst2]))

This is a apple
S6 许文秀 女 21 计算机系


In [20]:
#字符串转换为列表示例
#一是利用列表转换list(）；二是通过字符串的split()方法
str1='Python program'
result1=list(str1) #list转换
print(result1)
result2=str1.split()#默认空格分隔
print(result2)
result3=str1.split(',')#逗号分隔
print(result3)

['P', 'y', 't', 'h', 'o', 'n', ' ', 'p', 'r', 'o', 'g', 'r', 'a', 'm']
['Python', 'program']
['Python program']


- 数组与字符串相互转换

In [22]:
# 数组转换为字符串示例
import numpy as np
lst=['This','is','a','program']
arr=np.array(lst) 
str1=''.join(arr)
print(str1)

Thisisaprogram


In [23]:
# 字符串转换为数组示例
import numpy as np
str1='567232'
lst=list(str1)
arr1=np.array(lst)
print(arr1)

['5' '6' '7' '2' '3' '2']


- 列表和数组的相互转换

In [24]:
# 列表转换为数组示例
import numpy as np
lst1=[-3,4,8,6]
lst2=[[2,3,4],[4,7,1]]
arr1=np.array(lst1)
arr2=np.array(lst2)
print(arr1)
print(arr2)

[-3  4  8  6]
[[2 3 4]
 [4 7 1]]


In [25]:
# 数组转换为列表示例
import numpy as np
arr1=np.array([-3,4,8,6])
arr2=np.array([[2,3,4],[4,7,1]])
lst1=arr1.tolist()
lst2=arr2.tolist()
print(lst1)
print(lst2)

[-3, 4, 8, 6]
[[2, 3, 4], [4, 7, 1]]


- 列表和矩阵相互转换

In [26]:
# 列表转换为矩阵示例
import numpy as np
lst = [[1, 2, 3], [4, 5, 6]]
matr = np.mat(lst)  
print(type(matr))
print(matr)

<class 'numpy.matrix'>
[[1 2 3]
 [4 5 6]]


- 数组和矩阵相互转换

In [27]:
#数组转换为矩阵与列表转换为矩阵相同，而矩阵转换为数组与列表转换为数组相同。

### 3.1.5 数组元素和切片

In [28]:
# 一维数组元素和切片示例
import numpy as np
arr=np.array([-4,8,12,6,9,11,25])
print(arr[4])  #输出下标为4的元素
print(arr[2:5]) #输出下标为2,3,4的元素
print(arr[1:5:2]) #输出下标为1,3的元素（1到5但5不可取，且步长为2）

9
[12  6  9]
[8 6]


- 多维数组元素和切片

In [30]:
# 多维数组元素和切片示例
import numpy as np
arr=np.arange(12).reshape([3,4])
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [31]:
print(arr[1,2])  #输出下标为[1,2]的元素
print(arr[1:,2:]) #输出行标为1,2列标为2,3的元素
print(arr[::2,1]) #输出行标为0,2列标为1的元素

6
[[ 6  7]
 [10 11]]
[1 9]


In [37]:
import numpy as np
arr=np.arange(16).reshape([4,4])
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [40]:
print(arr[1:3,1:3])#取1、2行1、2列的元素

[[ 5  6]
 [ 9 10]]
